[workspace]
authors = ["Scott Henderson"]
channels = ["conda-forge"]
description = "Notes and code to understand and successfully perform accurate 3D coordinate reference system (CRS) transformations"
name = "3D_CRS_Transformation_Resources"
platforms = ["osx-arm64","linux-64"]
version = "0.1.0"

[tasks]
serve='myst start --execute'
build='myst build --execute --html'
check-links='myst build --check-links'
pdf='myst build --pdf'
spellcheck='codespell --skip  _build,references.bib'

[dependencies]
codespell = ">=2.4.1,<3"
dask = ">=2025.12.0,<2026"
gdal = ">=3.12.0,<4"
geopandas = ">=1.1.1,<2"
ipython = ">=9.8.0,<10"
ipykernel = ">=7.1.0,<8"
jupytext = ">=1.18.1,<2"
jupyterlab-myst = ">=2.6.0,<3"
libgdal-arrow-parquet = ">=3.12.0,<4"
matplotlib = ">=3.10.8,<4"
mystmd = ">=1.8.2,<2"
xarray = ">=2025.12.0,<2026"
rioxarray = ">=0.20.0,<0.21"
cartopy = ">=0.25.0,<0.26"
